### ISSUE TITLE
Official Version

### ISSUE THREAD

**Issue by jsenecal** [finish06/pyunifi#10]
I know that the original project is on pypi as well, but perhaps this one could become the official one since it is now maintained. Maybe tell the original author to link to this project in his documentation ?

**Comment by finish06** [comment]
Please see the included link: https://pypi.python.org/pypi/pyunifi/2.13

**Comment by jsenecal** [comment]
Yes, I know that pyunifi is on pypi, what I meant is to get in touch with the original author so that a link to this fork is put into it's readme

**Comment by finish06** [comment]
I emailed the original author and did not receive any feedback.
