### ISSUE TITLE
get_aps() is a misleading method name

### ISSUE THREAD

**Issue by FunkyLoveCow** [finish06/pyunifi#37]
The [`get_aps()`](https://github.com/finish06/pyunifi/blob/37c60c94c0903cff64ff33e8bee6b3abb2e10b78/pyunifi/controller.py#L183) is a misleading name. This method is returning all devices the controller knows about for the site, not just the APs. 

I suggestion a name like `get_devices()` instead

(Apologies for two issues back to back)

**Comment by finish06** [comment]
I am opposed to changing this considering I suspect many people have code that already references the original function name.  I will make a change to the code comments though on the function.  I will change it to read "all devices."
