### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by MichellBernardiS** [finish06/pyunifi#47]
Excuse me Sir, currently i am having thesis about python scripting with UBNT and i'm quite new to UBNT because i just learn with Mikrotik. I want to asking some questions, can you help me?
1. Can this script works on ubnt devices like rocket m2?
2. Can rocket m2 use controller like any other device?

Thanks. Any answer will help me a lot

**Comment by finish06** [comment]
This package is specific to Unifi and does not include other products such as the Rocket M2.  I have minimal knowledge of devices outside of Ubiquiti's Unifi line, however I am under the impression that the Rocket M2 cannot use the Unifi controller.

**Comment by MichellBernardiS** [comment]
Alright Sir, thanks for your information and feedback. I will try to use the Unifi devices then.
