### ISSUE TITLE
SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed

### ISSUE THREAD

**Issue by riahc3** [finish06/pyunifi#51]
Im getting this error:

requests.exceptions.SSLError: HTTPSConnectionPool(host='192.168.111.78', port=8443): Max retries exceeded with url: /api/login (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)'),))

**Comment by riahc3** [comment]
Also

requests.exceptions.SSLError: HTTPSConnectionPool(host='192.168.111.78', port=8443): Max retries exceeded with url: /api/login (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

**Comment by maxirus** [comment]
See `ssl_verify` in the [Constructor](https://github.com/finish06/pyunifi#__init__self-host-username-password).

**Comment by finish06** [comment]
@riahc3 I am going to close this ticket as setting ssl_verify to false should fix the issue. Please open a new ticket if needed. Thanks.
