### ISSUE TITLE
List or query multiple sites

### ISSUE THREAD

**Issue by superfishlu** [finish06/pyunifi#57]
Hello,

As per the documentation, we need to give the site ID when connecting to the controller.
Is it possible to list the controller for sites and query multiple sites? E.g. search for a client across all sites or create a given setting for all existing sites on the controller?
Likewise, can one create a new site with this API client?

Thanks a lot.

**Comment by finish06** [comment]
Per my understanding of API, that would not be possible because the API URL needs the site ID.  However, the work around would be to use the `get_sites` method.  Then loop through the different sites searching for clients, settings, etc.
