### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by Jeppedy** [finish06/pyunifi#59]
Any idea why I'm getting an error related to SSL?

from pyunifi.controller import Controller

c = Controller('192.168.2.126', 'JeffHerr', 'XXXXXX')
for ap in c.get_aps():
	print('AP named %s with MAC %s', ap.get('name'), ap['mac'])

requests.exceptions.SSLError: HTTPSConnectionPool(host='192.168.2.126', port=8443): Max retries exceeded with url: /api/login (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')])")))

I'm using a self-signed cert, I suppose, as I don't have a formal cert assigned.

**Comment by finish06** [comment]
Try setting the SSL variable to False as default is true.  Only officially signed certs are acceptable by default.

**Comment by finish06** [comment]
Closing issue as no response.
