### ISSUE TITLE
InsecureRequestWarning spams log

### ISSUE THREAD

**Issue by zissou1** [finish06/pyunifi#60]
Hello!
Maybe dumb question but is following necessary?:
```
if ssl_verify is False:
warnings.simplefilter("default", category=requests.packages.
urllib3.exceptions.
InsecureRequestWarning)
```

My Home Assistant core log is getting spammed by these warnings.

**Comment by finish06** [comment]
What version of HomeAssistant are you using?  This was replaced in HA by another project that is async and specifically maintained for HA.

**Comment by zissou1** [comment]
Ahaa, ok! Sorry didnt know that. Im running the latest stable release so its definately replaced then..
